#Eigenentwicklung
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_Password: ruan$ifa
      MYSQL_DATABASE: luxury_rents
      MYSQL_User: ruan
      MYSQL_Password: ruan$ifa  
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql

    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      restart: always
      ports:
        - 80:80 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    flask:
      image: snickch/flask001:v2
      container_name: flask
      restart: always
      expose:
        - 8000
      volumes:
        - ./app:/app:ro
      command: gunicorn -b localhost:8000 -w 4 luxury_rents:app
      depends_on:
        - "db"

                                                                                                                                                                                              
                                                                                                                                                                                               

