"""empty message

Revision ID: 0c33c07e5025
Revises: 
Create Date: 2023-03-06 18:51:09.115116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c33c07e5025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cars_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_cars_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cars_status'))
        batch_op.drop_index(batch_op.f('ix_cars_price'))
        batch_op.drop_index(batch_op.f('ix_cars_notes'))
        batch_op.drop_index(batch_op.f('ix_cars_model'))
        batch_op.drop_index(batch_op.f('ix_cars_date'))
        batch_op.drop_index(batch_op.f('ix_cars_customer'))

    op.drop_table('cars')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
